import BarChart from "../components/BarChart";
import DoughnutChart from "../components/DoughnutChart";
import LineChart from "../components/LineChart";
import { CSVLink } from "react-csv";
import { useRef } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useSelector } from "react-redux";

export default function Reports() {
    const transactions = useSelector((state) => state.transactions);
    const budgets = useSelector((state) => state.budgets);

    //refs for chart
    const doughnutRef = useRef(null);
    const lineRef = useRef(null);
    const barRef = useRef(null);

    //totals
    const totalIncome = transactions
        .filter((t) => t.type === "income")
        .reduce((sum, t) => sum + Number(t.amount), 0);

    const totalExpense = transactions
        .filter((t) => t.type === "expense")
        .reduce((sum, t) => sum + Number(t.amount), 0);

    //group transactions by category
    const expenseOnly = transactions.filter((t) => t.type === "expense");

    const categoryTotals = expenseOnly.reduce((obj, t) => {
        obj[t.category] = (obj[t.category] || 0) + Number(t.amount);
        return obj;
    }, {});

    const categories = Object.entries(categoryTotals).map(([name, amount]) => ({ name, amount }));

    //PDF Exporting
    const exportPDF = () => {
        const doc = new jsPDF();

        //title
        doc.setFontSize(22)
        doc.setTextColor(233, 30, 99);
        doc.text("Budget Lens Report", 14, 20)

        doc.setFontSize(14)
        doc.setTextColor(63, 81, 181);
        doc.text("Monthly Financial Summary", 14, 30)

        //summary
        doc.setFontSize(12)
        doc.setTextColor(0, 0, 0);
        doc.text(`Total Income : INR ${totalIncome} `, 14, 45)
        doc.text(`Total Expenses : INR ${totalExpense} `, 14, 55)
        doc.setTextColor(34, 197, 94);
        doc.text(`Savings : INR ${totalIncome - totalExpense} `, 14, 65)

        //category breakdown table
        autoTable(doc, {
            head: [["Category", "Amount"]],
            body: categories.map(c => [c.name, c.amount]),
            startY: 80,
            styles: { fontSize: 10, cellPadding: 4 },
            headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255], fontStyle: "bold" },
            alternateRowStyles: { fillColor: [250, 250, 250] }
        });

        //charts as images
        //console.log("Doughnut ref:", doughnutRef.current);
        //console.log("Bar ref:", barRef.current);
        //console.log("Line ref:", lineRef.current);
        if (doughnutRef.current && doughnutRef.current.canvas) {
            const imgData = doughnutRef.current.canvas.toDataURL("image/png");
            doc.addImage(imgData, "PNG", 14, doc.lastAutoTable.finalY + 20, 60, 80)
        }

        if (barRef.current && barRef.current.canvas) {
            const imgData = barRef.current.canvas.toDataURL("image/png");
            doc.addImage(imgData, "PNG", 110, doc.lastAutoTable.finalY + 20, 60, 80)
        }
        if (lineRef.current && lineRef.current.canvas) {
            const imgData = lineRef.current.canvas.toDataURL("image/png");
            doc.addImage(imgData, "PNG", 14, doc.lastAutoTable.finalY + 120, 150, 60)
        }

        //footer
        doc.setFontSize(10)
        doc.setTextColor(150);
        doc.text("Generated by Budget Lens", 14, 290)

        doc.save("Report.pdf")
    }

    //CSV Data
    const csvData = transactions.map((t) => ({
        Date: new Date(t.date).toLocaleDateString("en-IN"),
        Category: t.category,
        Description: t.note,
        Amount:
            t.type === "income"
                ? `+${t.amount}`
                : `-${t.amount}`,
        Mode: t.mode,
    }));

    return (
        <div className="min-h-screen px-4 sm:px-8 py-8 bg-linear-to-br from-[#0f0c29] via-[#1a1333] to-[#0f0c29] text-gray-300">

            <div className="mb-10">

                {/* Title */}
                <h1 className="text-3xl font-bold text-center bg-linear-to-r from-purple-400 to-emerald-400 bg-clip-text text-transparent">
                    Reports & Analytics
                </h1>

                {/* Buttons */}
                <div className="flex justify-end gap-4 mt-6">

                    <CSVLink
                        data={csvData}
                        filename="Transactions.csv"
                        className="px-5 py-2 rounded-lg font-medium bg-linear-to-r from-purple-600 to-indigo-600 hover:scale-105 transition-all duration-300 shadow-lg shadow-purple-600/30">
                        Download CSV
                    </CSVLink>

                    <button
                        onClick={exportPDF}
                        className="px-5 py-2 rounded-lg font-medium bg-linear-to-r from-emerald-400 to-teal-500 text-black hover:scale-105 transition-all duration-300 shadow-lg shadow-emerald-500/30">
                        Export PDF
                    </button>

                </div>
            </div>

            {/* CHART GRID */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

                {/* Doughnut Chart */}
                <div className="bg-white/5 backdrop-blur-xl border border-purple-900/30 rounded-2xl p-6 shadow-xl">

                    <h2 className="text-lg font-medium mb-4 text-gray-200">
                        Spending Breakdown
                    </h2>

                    <div className="h-80">
                        <DoughnutChart ref={doughnutRef} />
                    </div>
                </div>

                {/* Bar Chart */}
                <div className="bg-white/5 backdrop-blur-xl border border-purple-900/30 rounded-2xl p-6 shadow-xl">

                    <h2 className="text-lg font-medium mb-4 text-gray-200">
                        Income vs Expense
                    </h2>

                    <div className="h-80">
                        <BarChart ref={barRef} />
                    </div>
                </div>
            </div>

            {/* Line Chart */}
            <div className="mt-8 bg-white/5 backdrop-blur-xl border border-purple-900/30 rounded-2xl p-6 shadow-xl">

                <h2 className="text-lg font-medium mb-4 text-gray-200">
                    Spending Trend
                </h2>

                <div className="h-96">
                    <LineChart ref={lineRef} />
                </div>
            </div>

        </div>
    );
}