import BarChart from "../components/BarChart";
import DoughnutChart from "../components/DoughnutChart";
import LineChart from "../components/LineChart"
import { CSVLink } from "react-csv"
import { useRef } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useSelector } from "react-redux";

export default function Reports() {
    const transactions = useSelector((state) => state.transactions);
    const budgets = useSelector((state) => state.budgets);

    //refs for chart
    const doughnutRef = useRef(null);
    const lineRef = useRef(null);
    const barRef = useRef(null);

    //totals
    const totalIncome = transactions.filter((t) => t.type === "income")
        .reduce((sum, t) => sum + t.amount, 0);
    const totalExpense = transactions.filter((t) => t.type === "expense")
        .reduce((sum, t) => sum + t.amount, 0);

    //group transactions by category
    const expenseOnly = transactions.filter((t) => t.type === "expense");

    const categoryTotals = expenseOnly.reduce((obj, t) => {
        obj[t.category] = (obj[t.category] || 0) + Number(t.amount);
        return obj;
    }, {});

    const categories = Object.entries(categoryTotals).map(([name, amount]) => ({ name, amount }));

    const exportPDF = () => {
        const doc = new jsPDF();

        //title
        doc.setFontSize(22)
        doc.setTextColor(233, 30, 99);
        doc.text("Budget Lens Report", 14, 20)

        doc.setFontSize(14)
        doc.setTextColor(63, 81, 181);
        doc.text("Monthly Financial Summary", 14, 30)

        //summary
        doc.setFontSize(12)
        doc.setTextColor(0, 0, 0);
        doc.text(`Total Income : INR ${totalIncome} `, 14, 45)
        doc.text(`Total Expenses : INR ${totalExpense} `, 14, 55)
        doc.setTextColor(34, 197, 94);
        doc.text(`Savings : INR ${totalIncome - totalExpense} `, 14, 65)

        //category breakdown table
        autoTable(doc, {
            head: [["Category", "Amount"]],
            body: categories.map(c => [c.name, c.amount]),
            startY: 80,
            styles: { fontSize: 10, cellPadding: 4 },
            headStyles: { fillColor: [99, 102, 241], textColor: [255, 255, 255], fontStyle: "bold" },
            alternateRowStyles: { fillColor: [250, 250, 250] }
        });

        //charts as images
        //console.log("Doughnut ref:", doughnutRef.current);
        //console.log("Bar ref:", barRef.current);
        //console.log("Line ref:", lineRef.current);
        if (doughnutRef.current && doughnutRef.current.canvas) {
            const imgData = doughnutRef.current.canvas.toDataURL("image/png");
            doc.addImage(imgData, "PNG", 14, doc.lastAutoTable.finalY + 20, 60, 80)
        }

        if (barRef.current && barRef.current.canvas) {
            const imgData = barRef.current.canvas.toDataURL("image/png");
            doc.addImage(imgData, "PNG", 110, doc.lastAutoTable.finalY + 20, 60, 80)
        }
        if (lineRef.current && lineRef.current.canvas) {
            const imgData = lineRef.current.canvas.toDataURL("image/png");
            doc.addImage(imgData, "PNG", 14, doc.lastAutoTable.finalY + 120, 150, 60)
        }

        //footer
        doc.setFontSize(10)
        doc.setTextColor(150);
        doc.text("Generated by Budget Lens", 14, 290)

        doc.save("Report.pdf")
    }

    const csvData = transactions.map((t) => (
        {
            Date: new Date(t.date).toLocaleDateString("en-IN"), 
            Category: t.category,
            Description: t.note,
            Amount: t.type === "income" ? `+${t.amount}` : `-${t.amount}`,
            Mode: t.mode
        }
    ))
    return (
        <div className="min-h-screen space-y-6 p-6 bg-linear-to-br from-indigo-100 to-purple-100">

            <h1 className=" text-2xl text-center text-pink-600 font-bold mb-2">Reports and Analytics</h1>

            {/*Download reports as csv and pdf*/}
            <div className="flex space-x-5 items-end justify-end">
                <CSVLink data={csvData} filename="Transactions.csv"
                    className="px-4 py-2 bg-linear-to-r from-purple-500 to-pink-500 text-white rounded-md font-semibold hover:opacity-90">
                    Download CSV</CSVLink>
                <button onClick={exportPDF}
                    className="px-4 py-2 bg-linear-to-r from-purple-500 to-pink-500 text-white rounded-md font-semibold hover:opacity-90">Download PDF</button>
            </div>

            <div className="text-md text-purple-900 font-semibold">Monthly View</div>

            <div className="mt-3 flex space-x-5">

                {/*Doughnut Chart that shows expenses*/}
                <div className="bg-white w-1/2 rounded-xl shadow p-4">
                    <h2 className="text-lg font-semibold">Spending Breakdown</h2>
                    <DoughnutChart ref={doughnutRef} />
                </div>

                {/*Bar Chart that compare expense and income*/}
                <div className="bg-white w-1/2 rounded-xl shadow p-4">
                    <h2 className="text-lg font-semibold">Income v/s Expense</h2>
                    <BarChart ref={barRef} />
                </div>
            </div>

            {/*Line Chart that shows Spending and Earning*/}
            <div className="bg-white rounded-xl shadow p-4">
                <h2 className="text-lg font-semibold">Spending as Graph</h2>
                <LineChart ref={lineRef} />
            </div>

        </div>
    )
}